### ISSUE TITLE
Exception during sync

### ISSUE THREAD

**Issue by nebuchar** [MediaBrowser/trakt#18]
With version 3.4.7.0 I get the error **Sync library to trakt.tv failed**

Looking in the logs I have this

> 2021-03-29 02:00:00.007 Info HttpClient: POST https://api.trakt.tv/oauth/token
2021-03-29 02:00:00.765 Info HttpClient: POST https://api.trakt.tv/oauth/token
2021-03-29 02:00:01.431 Info HttpClient: POST https://api.trakt.tv/oauth/token
2021-03-29 02:00:01.589 Error Trakt: Exception handled
	*** Error Report ***
	Version: 4.5.4.0
	Command line: /app/emby/EmbyServer.dll -programdata /config -ffdetect /app/emby/ffdetect -ffmpeg /app/emby/ffmpeg -ffprobe /app/emby/ffprobe -restartexitcode 3
	Operating system: Linux version 5.10.17-v7l+ (dom@buildbot) (arm-linux-gnueabihf-gcc-8 (Ubuntu/Linaro 8.4.0-3ubuntu1) 8.4.0, GNU ld (GNU Binutils for Ubuntu) 2.34) #140
	Framework: .NET Core 3.1.8
	OS/Process: arm/arm
	Runtime: app/emby/System.Private.CoreLib.dll
	Processor count: 4
	Data path: /config
	Application path: /app/emby
	System.Exception: System.Exception: Post failed
	   at Trakt.Api.TraktApi.PostToTrakt(String url, Object data, CancellationToken cancellationToken, TraktUser traktUser)
	   at Trakt.Api.TraktApi.RefreshUserAuth(TraktUser traktUser, CancellationToken cancellationToken)
	   at Trakt.Api.TraktApi.SetRequestHeaders(HttpRequestOptions options, TraktUser traktUser, CancellationToken cancellationToken)
	   at Trakt.Api.TraktApi.GetFromTrakt(String url, CancellationToken cancellationToken, TraktUser traktUser)
	   at Trakt.Api.TraktApi.SendGetAllWatchedMoviesRequest(TraktUser traktUser, CancellationToken cancellationToken)
	   at Trakt.ScheduledTasks.SyncFromTraktTask.SyncTraktDataForUser(User user, Double currentProgress, CancellationToken cancellationToken, IProgress`1 progress, Double percentPerUser)
	Source: Trakt
	TargetSite: Void MoveNext()
	
> 2021-03-29 02:00:01.608 Error Trakt: Error syncing trakt data for user ###
	*** Error Report ***
	Version: 4.5.4.0
	Command line: /app/emby/EmbyServer.dll -programdata /config -ffdetect /app/emby/ffdetect -ffmpeg /app/emby/ffmpeg -ffprobe /app/emby/ffprobe -restartexitcode 3
	Operating system: Linux version 5.10.17-v7l+ (dom@buildbot) (arm-linux-gnueabihf-gcc-8 (Ubuntu/Linaro 8.4.0-3ubuntu1) 8.4.0, GNU ld (GNU Binutils for Ubuntu) 2.34) #140
	Framework: .NET Core 3.1.8
	OS/Process: arm/arm
	Runtime: app/emby/System.Private.CoreLib.dll
	Processor count: 4
	Data path: /config
	Application path: /app/emby
	System.Exception: System.Exception: Post failed
	   at Trakt.Api.TraktApi.PostToTrakt(String url, Object data, CancellationToken cancellationToken, TraktUser traktUser)
	   at Trakt.Api.TraktApi.RefreshUserAuth(TraktUser traktUser, CancellationToken cancellationToken)
	   at Trakt.Api.TraktApi.SetRequestHeaders(HttpRequestOptions options, TraktUser traktUser, CancellationToken cancellationToken)
	   at Trakt.Api.TraktApi.GetFromTrakt(String url, CancellationToken cancellationToken, TraktUser traktUser)
	   at Trakt.Api.TraktApi.SendGetAllWatchedMoviesRequest(TraktUser traktUser, CancellationToken cancellationToken)
	   at Trakt.ScheduledTasks.SyncFromTraktTask.SyncTraktDataForUser(User user, Double currentProgress, CancellationToken cancellationToken, IProgress`1 progress, Double percentPerUser)
	   at Trakt.ScheduledTasks.SyncFromTraktTask.Execute(CancellationToken cancellationToken, IProgress`1 progress)
	Source: Trakt
	TargetSite: Void MoveNext()

**Comment by LukePulverenti** [comment]
HI, can you try the 3.4.8 update that went out? Thanks.

**Comment by nebuchar** [comment]
Hello, it still happens with 3.4.8

**Comment by LukePulverenti** [comment]
Hi, are you still having an issue with this?

**Comment by LukePulverenti** [comment]
Closing, but please feel free to re-open if you're still having an issue. Thanks.
